# Cleaning Notebook of the Data

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("Cleaning_Combined.xlsx")
df.head()

,BET_m2g,pore_vol_cm3g,pH_pzc,C_pct,H_pct,O_pct,N_pct,C0_mgL,pH,dose_gL,contact_time_min,temp_K,Ce_mgL,qe_mgg
0,950.0,0.80,NaN,NaN,NaN,NaN,NaN,150.0,6.0,1.2,240,298,NaN,115
1,950.0,0.80,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.2,60,298,NaN,162.33
2,950.0,0.80,NaN,NaN,NaN,NaN,NaN,150.0,5.0,1.2,60,298,10.56,116.2
3,950.0,0.80,NaN,NaN,NaN,NaN,NaN,150.0,5.0,1.2,60,318,18.195,109.84
4,1559.9,1.71,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.4,120,298,NaN,80.6

In [3]:
df.describe()

,BET_m2g,pore_vol_cm3g,pH_pzc,C_pct,H_pct,O_pct,N_pct,C0_mgL,pH,dose_gL
count,183.000000,182.000000,130.000000,38.000000,32.000000,38.000000,43.000000,110.000000,147.000000,166.000000
mean,1031.406545,0.683740,6.741000,62.457105,4.491875,29.626316,21.939767,84.393273,28.561224,187.021952
std,604.179270,0.419091,1.910562,22.457184,1.576862,22.462659,48.660238,87.058720,95.598913,593.845031
min,67.810000,0.054000,2.800000,35.230000,2.500000,3.810000,0.300000,1.000000,0.800000,0.100000
25%,597.200000,0.268858,6.000000,35.230000,3.892500,9.610000,0.470000,10.000000,4.000000,0.500000
50%,1098.000000,0.708000,6.400000,69.700000,4.480000,20.340000,1.160000,50.000000,6.000000,2.000000
75%,1498.000000,0.940000,7.695000,82.080000,4.480000,59.820000,2.170000,150.000000,7.000000,120.000000
max,2871.000000,1.710000,12.200000,93.100000,8.000000,59.820000,200.000000,300.000000,500.000000,3000.000000